services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  worker:
    build: ./backend
    command: celery -A app.main.celery worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
  flower:
    build: ./backend
    command: celery -A app.main.celery flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
      - worker
  redis:
    image: redis:8
    ports:
      - "6379:6379"